version: 2.1

jobs:
  run-application:
    macos:
      xcode: 13.3.1  # Specify the Xcode version you need
    steps:
      - checkout:
          path: ~/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            brew install python@3.8
            export PATH="/usr/local/opt/python@3.8/bin:$PATH"
            ln -s /usr/local/opt/python@3.8/bin/python3 /usr/local/bin/python
            ln -s /usr/local/opt/python@3.8/bin/pip3 /usr/local/bin/pip
            https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-amd64
            sudo hdiutil attach Docker.dmg
            sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
            sudo hdiutil detach /Volumes/Docker

      - run:
          name: "Set environment variables"
          command: |
            cd ~/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master

      - run:
          name: "Build"
          command: |     
            pwd
            ls
            ls devstack
            python --version
            pip --version
            make --version
            docker --version
            docker-compose --version
            # Your macOS-specific build commands go here

workflows:
  run-application-workflow:
    jobs:
      - run-application
