version: 2.1

executors:
  adg-edx-executor:
    docker:
      - image: cimg/python:3.5-node

commands:
  run-hello-world:
    steps:
      - checkout
      - run:
          name: Run Docker Hello World
          command: |
            docker run hello-world

jobs:
  run-hello-world:
    executor: adg-edx-executor
    steps:
      - run-hello-world
