version: 2.1

jobs:
  run-application:
    macos:
      xcode: 12.5.1  # Specify the Xcode version you need
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            # Your macOS-specific commands go here

      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master

      - run:
          name: "Build"
          command: |     
            pwd
            ls
            # Your macOS-specific build commands go here

workflows:
  run-application-workflow:
    jobs:
      - run-application
