version: 2.1

jobs:
  run-application:
    docker:
      - image: docker:latest
        environment:
            DOCKER_DRIVER: overlay2
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |         
            apk add --no-cache git make docker-compose
            python3 --version
            pip3 --version
            #ln -sf /usr/bin/python3.11 /usr/bin/python
            #python -m ensurepip
            #ln -sf /usr/bin/pip3.11 /usr/bin/pip
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Build"
          command: |
            #pwd
            #ls
            #ls devstack
            python --version
            pip --version
            make --version
            docker --version
            docker-compose --version
            #sudo service docker start
            #sudo docker run hello-world
            #docker info | grep -i 'storage driver'
            #cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make studio-shell
            #pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
