version: 2.1

jobs:
  run-application:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            apt-get install -y python3 python3-pip
            ln -sf /usr/bin/python3 /usr/bin/python
            ln -sf /usr/bin/pip3 /usr/bin/pip
            # Additional commands to install other dependencies if needed
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Build"
          command: |       
            python --version
            pip --version
            make --version
            docker --version
            docker-compose --version
            cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make studio-shell
            #pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
