version: 2.1

jobs:
  run-application:
    docker:
      - image: docker:latest
        environment:
            DOCKER_DRIVER: overlay2
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |         
            apk add --no-cache git make docker-compose python3 bash
            ln -sf /usr/bin/python3 /usr/bin/python
            python -m ensurepip
            ln -sf /usr/bin/pip3 /usr/bin/pip

            python --version
            pip --version
            make --version
            docker --version
            docker-compose --version
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Build"
          command: |
            dockerd
            docker run hello-world
            #cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make studio-shell
            #pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
