version: 2.1

jobs:
  run-application:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout:
          path: /root/project/devstack
          #ref: nutmeg.master  # Specify the branch directly
      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Build"
          command: |
            pwd
            ls
            cd devstack
            ls devstack
            # make requirements
            # make dev.clone
            # make dev.pull.large-and-slow
            # make dev.provision
            # make dev.up.large-and-slow
            # make studio-shell
            # pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
