version: 2.1

jobs:
  run-application:
    docker:
      - image: docker:19.03.13
    steps:
      - checkout:
          path: /root/project  # Specify the desired path
      - run:
          name: "Clone repository and set working directory"
          command: |
            cd /root/project
            git init
            git remote add origin https://github.com/openedx/devstack.git
            git fetch --depth 1 origin nutmeg.master
            git checkout -b nutmeg.master origin/nutmeg.master
      - run:
          name: "Install Dependencies"
          command: |
            apk add --no-cache make docker-compose
            # Additional commands to install other dependencies if needed
      - run:
          name: "Set environment variables"
          command: |
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Run application"
          command: |
            pwd
            ls
            #cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make dev.stop

workflows:
  run-application-workflow:
    jobs:
      - run-application
