version: 2.1

jobs:
  run-application:
    macos:
      xcode: 14.2.0  # Specify the Xcode version you need
    steps:
      - checkout:
          path: ~/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            brew install python@3.8
            export PATH="/usr/local/opt/python@3.8/bin:$PATH"
            ln -s /usr/local/opt/python@3.8/bin/python3 /usr/local/bin/python
            ln -s /usr/local/opt/python@3.8/bin/pip3 /usr/local/bin/pip
            #curl -o Docker.dmg https://desktop.docker.com/mac/stable/Docker.dmg
            #sudo hdiutil attach Docker.dmg
            #sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
            #sudo hdiutil detach /Volumes/Docker

      - run:
          name: "Set environment variables"
          command: |
            cd ~/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master

      - run:
          name: "Build"
          command: |     
            pwd
            ls
            ls devstack
            python --version
            pip --version
            make --version
            #docker --version
            #docker-compose --version
            # Your macOS-specific build commands go here

workflows:
  run-application-workflow:
    jobs:
      - run-application
