version: 2.1

jobs:
  run-application:
    docker:
      - image: docker:19.03.13
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            apk add --no-cache make docker-compose
            #ln -sf /usr/bin/python3.8 /usr/bin/python
            #ln -sf /usr/bin/pip3.8 /usr/bin/pip
            # Additional commands to install other dependencies if needed
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Run application"
          command: |
            pip --version
            python3 --version
            make --version
            docker-compose --version
            docker --version
            #cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make studio-shell
            #pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
