version: 2.1

jobs:
  run-application:
    macos:
      xcode: 13.4.1  # Specify the Xcode version you need
    steps:
      - checkout:
          path: ~/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            brew install python@3.8
            export PATH="/usr/local/opt/python@3.8/bin:$PATH"
            ln -s /usr/local/opt/python@3.8/bin/python3 /usr/local/bin/python
            ln -s /usr/local/opt/python@3.8/bin/pip3 /usr/local/bin/pip
            brew install --cask docker
            brew install docker-compose
      - run:
          name: "Set environment variables"
          command: |
            cd ~/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master

      - run:
          name: "Build"
          command: |     
            pwd
            ls
            ls devstack
            python --version
            pip --version
            make --version
            docker --version
            docker-compose --version
            # Your macOS-specific build commands go here

workflows:
  run-application-workflow:
    jobs:
      - run-application
