version: 2.1

jobs:
  run-hello-world:
    docker:
      - image: docker:20.10.10
    steps:
      - checkout
      - run:
          name: Run Docker Hello World
          command: |
            docker run hello-world

workflows:
  version: 2
  main:
    jobs:
      - run-hello-world
