version: 2.1

jobs:
  run-application:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout:
          path: /root/project/devstack
          ref: nutmeg.master  # Specify the branch directly
      - run:
          name: "Install Dependencies"
          command: |
            export DEBIAN_FRONTEND=noninteractive
            # Add Docker's official GPG key:
            apt-get update
            apt-get install -y sudo systemctl ca-certificates curl gnupg
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
            
            # Add the repository to Apt sources:
            echo \
              "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update            
            apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin            
            apt-get install -y python3.8 python3.8-distutils python3-pip
            apt-get install --only-upgrade iptables
            ln -sf /usr/bin/python3 /usr/bin/python
            ln -sf /usr/bin/pip3 /usr/bin/pip
      - run:
          name: "Set environment variables"
          command: |
            cd /root/project/devstack
            export DEVSTACK_WORKSPACE="$(pwd)"
            export OPENEDX_RELEASE=nutmeg.master
      - run:
          name: "Build"
          command: |
            python --version
            pip --version
            make --version
            docker --version
            sudo usermod -aG docker $USER
            sudo systemctl status docker
            sudo docker run hello-world
            docker info | grep -i 'storage driver'
            #cd devstack
            #make requirements
            #make dev.clone
            #make dev.pull.large-and-slow
            #make dev.provision
            #make dev.up.large-and-slow
            #make studio-shell
            #pytest cms

workflows:
  run-application-workflow:
    jobs:
      - run-application
